# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: Default
  vmImage: valentin

stages:
  - stage: docker_push
    displayName: BuildAndPush
    jobs:
      - job:
        displayName: BuildDockerAndPush
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHubVal'
              repository: 'shinratsu/raycasting'
              command: 'buildAndPush'
              Dockerfile: './api/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)
  - stage: deploy
    displayName: 'Deploy to dev env'
    dependsOn: docker_push
    jobs:
    - job: 
      displayName: test
      steps:
        - script: echo 'hello world'
    - deployment: DeployAPIs
      displayName: Deploy a docker image to SIGMA computer
      environment:
        name: ValentinEnvironment
        resourceName: SIGMA
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                docker stop $(docker ps -a -q)
                docker run  -p 3000:3000 --name api_websocket_raycasting$(Build.BuildId) -d shinratsu/raycasting:latest 