# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: Default
  vmImage: valentin

stages:
  - stage: Build
    displayName: BuildAndPush
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHubVal'
              repository: 'shinratsu/raycasting'
              command: 'buildAndPush'
              Dockerfile: './api/Dockerfile'
              tags: |
                latest
                $(Build.Build.Id)
  - stage:
    displayName: 'Deploy to dev env'
    dependsOn: Build
    jobs:        
    - deployment: DeployAPIs
      displayName: Deploy a docker image to on premise server
      environment: ValentinEnvironment
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                docker run  -p 8080:8080 --name api_websocket_raycasting$(Build.BuildId) -d shinratsu/raycasting:latest
